name: deploy

on:
  push:
    branches: [main]

permissions:
  # allow bot to create / push to gh-pages
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          # don't forget theme submodule
          submodules: recursive 
      - uses: peaceiris/actions-hugo@v2
        with: 
          hugo-version: '0.147.1' 
          extended: true
      - name: generate site 
        run: hugo
      - name: upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: public
          retention-days: 1 

  lint-md:
    runs-on: ubuntu-latest
    steps:
      - name: checkout site source
        uses: actions/checkout@v4
      - name: run markdown linter
        uses: DavidAnson/markdownlint-cli2-action@v19.1.0
        with:
          globs: '**/*.md'
          config: .markdownlint.yaml

  link-check:
    needs: [build, deploy]
    runs-on: ubuntu-latest
    steps:
      - name: download site build
        uses: actions/download-artifact@v4
        with: 
          name: site 
          path: ./public
      - name: link check (lychee) | link check live site
        uses: lycheeverse/lychee-action@v2.4.1
        with:
          args: >
            --base https://christianf.io
            --timeout 20
            --no-progress
            --verbose
            --accept 200,206
            --exclude '^https://www\.linkedin\.com'
            './public/**/*.html'


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download site build
        uses: actions/download-artifact@v4
        with: 
          name: site 
          path: ./public
      - name: deploy site to pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./public
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
